### ISSUE TITLE
Finish this up.

### ISSUE THREAD

**Issue by katamaritaco** [UW-UPL/Sample-C-Program-gofish#1]
Finish up the program.

Update the README.

Make it public.

Link to this in the /Talks repo.

**Comment by katamaritaco** [comment]
Once this is done, can free this Private Repo Up.

**Comment by jdetter** [comment]
I can help finish this up

**Comment by jdetter** [comment]
You can probably move this to a public repo now, it's almost done. I will take probably 2 or 3 hours tomorrow to really polish it up with comments and it will be finished.

**Comment by katamaritaco** [comment]
Move it over when you're finished please :+1: :+1:

**Comment by katamaritaco** [comment]
I'm going to make this public now.

**Comment by jdetter** [comment]
I'm pretty much done with this, I will have time to figure out small bugs later.
